#!/usr/bin/env python3
"""
SM64 Stage 2: emit the AICA Yamaha-ADPCM pool as a LINKED object (.bin + .s
incbin, no runtime file) plus a generated-C descriptor table.

Unlike MK64/OoT, sm64-dc links all sound data into the ELF, so the pool is a
linked symbol (gAicaAdpcmPool) rather than a dc_data/*.bin loaded at runtime.

Two sample classes:
  * normal (<=65534 samples): Yamaha ADPCM, uploaded to ARAM by the runtime
    per-sample cache. Played on a hardware voice. (None of SM64's normal
    samples need resampling; rate_scale is 0 except for FORCE_NOSTREAM keys.)
  * streamed (>65534 samples): too long for a single AICA channel (16-bit LEA).
    Kept full quality as Yamaha ADPCM in the resident pool; the SH4 streamer
    decodes them sequentially into a small ARAM ring at runtime. stream=1.

Lookup key (src_offset) = absolute byte offset into sound_data.tbl =
tblRegionOff(bank)+sampleAddr. Runtime derives it as
(patched sample->sampleAddr - gSoundDataRaw).
"""

import os
from multiprocessing import Pool
from pathlib import Path

from sm64_albank_parse import parse_all
from transcode import transcode_sample, transcode_resampled, beam_encode_cached, FMT_PCM16, FMT_PCM8, FMT_ADPCM, BEAM
import vadpcm
import ya2beam_c

ALIGN = 32
AICA_MAX = 65534
# Keys just over AICA_MAX to resample down to one PCM voice instead of streaming
# (two independent streams of one sound phase-comb). See transcode_resampled.
FORCE_NOSTREAM = {int(k, 16) for k in os.environ.get("AICA_FORCE_NOSTREAM", "114B20").replace(",", " ").split()}


def align_up(n, a):
    return (n + a - 1) & ~(a - 1)


def transcode_streamed(s):
    """Long sample: full-quality Yamaha ADPCM (beam-search), no decimation."""
    pcm = vadpcm.decode(s.data, s.codec, s.order, s.npredictors, s.book)
    adpcm, n = beam_encode_cached(pcm)
    loop_start, loop_end = (s.loop_start, s.loop_end) if s.has_loop else (0, n)
    return {
        "bank": s.bank, "addr": s.addr, "data": adpcm, "fmt": FMT_ADPCM,
        "snr": 99.0, "nsamples": n, "loop": bool(s.has_loop),
        "loop_start": loop_start, "loop_end": min(loop_end, n),
        "rate_scale": 0, "stream": 1,
    }


def _transcode_one(s):
    """Pool worker: one sample -> descriptor (no pool_offset yet)."""
    if s.addr in FORCE_NOSTREAM and s.nsamples > AICA_MAX:
        d = transcode_resampled(s, AICA_MAX)
    elif s.nsamples > AICA_MAX:
        d = transcode_streamed(s)
    else:
        d = transcode_sample(s)
        d["stream"] = 0
    d["key"] = s.addr
    return d


def main(ctl_path, tbl_path, outdir, incdir):
    outdir = Path(outdir)
    incdir = Path(incdir)
    _, samples = parse_all(ctl_path, tbl_path, with_data=True)

    # Per-sample transcode is independent and CPU-heavy (beam search) -- fan out
    # across all cores. Pool.map preserves order, and we re-sort by key before
    # laying out the pool, so output is deterministic regardless of scheduling.
    # Build the C encoder .so once here so forked workers inherit it (no per-worker
    # compile race); falls back to pure-Python if no C compiler is present.
    if not ya2beam_c.prebuild():
        print("sm64_emit: C beam encoder unavailable; using pure-Python (slow)")
    with Pool(os.cpu_count()) as pool:
        descs = pool.map(_transcode_one, list(samples.values()))

    descs.sort(key=lambda d: d["key"])

    blob = bytearray()
    for d in descs:
        d["pool_offset"] = len(blob)
        blob += d["data"]
        blob += b"\x00" * (align_up(len(blob), ALIGN) - len(blob))
    n_stream = sum(d["stream"] for d in descs)

    # integrity
    keys = [d["key"] for d in descs]
    assert keys == sorted(keys) and len(keys) == len(set(keys))
    for d in descs:
        assert blob[d["pool_offset"]:d["pool_offset"] + len(d["data"])] == d["data"]
        if not d["stream"]:
            assert d["nsamples"] <= AICA_MAX, (d["key"], d["nsamples"])
        assert 0 <= d["loop_start"] <= d["loop_end"] <= d["nsamples"]

    outdir.mkdir(parents=True, exist_ok=True)
    incdir.mkdir(parents=True, exist_ok=True)
    (outdir / "aica_pool.bin").write_bytes(blob)

    h = ["/* Auto-generated by tools/aica/sm64_emit.py. Do not edit. */",
         "#ifndef AICA_SAMPLE_TABLE_H", "#define AICA_SAMPLE_TABLE_H", "#include <stdint.h>", "",
         "typedef struct {",
         "    uint32_t src_offset;       /* absolute offset into sound_data.tbl (key) */",
         "    uint32_t pool_offset;      /* byte offset into gAicaAdpcmPool */",
         "    uint32_t byte_len;         /* Yamaha ADPCM byte length */",
         "    uint32_t nsamples;         /* PCM sample count (may exceed 65534 if streamed) */",
         "    uint32_t loop_start;",
         "    uint32_t loop_end;",
         "    uint8_t  loop_flag;",
         "    uint8_t  rate_scale;       /* playback-freq scale, /256 fixed (0 = none) */",
         "    uint8_t  stream;           /* 1 = too long for one channel; SH4-streamed */",
         "    uint8_t  fmt;              /* AICA_SM_* sample format: 0=PCM16 1=PCM8 2=ADPCM */",
         "} AicaSampleDesc;", "",
         f"#define AICA_SAMPLE_COUNT {len(descs)}",
         f"#define AICA_ADPCM_POOL_SIZE {len(blob)}u",
         "extern const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT];",
         "extern const uint8_t gAicaAdpcmPool[AICA_ADPCM_POOL_SIZE];", "", "#endif"]
    (incdir / "aica_sample_table.h").write_text("\n".join(h) + "\n")

    c = ["/* Auto-generated by tools/aica/sm64_emit.py. Do not edit. */",
         '#include "aica_sample_table.h"', "",
         "#ifdef TARGET_DC",
         "const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT] = {"]
    for d in descs:
        c.append(f"    {{ 0x{d['key']:06X}, 0x{d['pool_offset']:06X}, {len(d['data']):>6}, "
                 f"{d['nsamples']:>6}, {d['loop_start']:>6}, {d['loop_end']:>6}, "
                 f"{1 if d['loop'] else 0}, {d['rate_scale']}, {d['stream']}, {d['fmt']} }},")
    c.append("};")
    c.append("#endif")
    (outdir / "aica_sample_table.c").write_text("\n".join(c) + "\n")

    # Pool as a guarded C array (compiled into the ELF on the DC target).
    pc = ["/* Auto-generated by tools/aica/sm64_emit.py. Do not edit. */",
          '#include "aica_sample_table.h"', "",
          "#ifdef TARGET_DC",
          "const uint8_t gAicaAdpcmPool[AICA_ADPCM_POOL_SIZE] __attribute__((aligned(32))) = {"]
    line = []
    for n, b in enumerate(blob):
        line.append(f"{b}")
        if len(line) == 32:
            pc.append("    " + ",".join(line) + ",")
            line = []
    if line:
        pc.append("    " + ",".join(line) + ",")
    pc.append("};")
    pc.append("#endif")
    (outdir / "aica_pool.c").write_text("\n".join(pc) + "\n")

    n16 = sum(1 for d in descs if d["fmt"] == FMT_PCM16)
    n8 = sum(1 for d in descs if d["fmt"] == FMT_PCM8)
    nad = sum(1 for d in descs if d["fmt"] == FMT_ADPCM)
    from transcode import _HAVE_SCIPY
    print(f"sm64_emit: {len(descs)} descs  ADPCM={nad} PCM16={n16} PCM8={n8} (streamed={n_stream}), "
          f"pool {len(blob):,} B -> {outdir} (.c/.bin), {incdir} (.h)"
          f"{'' if _HAVE_SCIPY else '  [stdlib decimate fallback]'}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--ctl", required=True)
    ap.add_argument("--tbl", required=True)
    ap.add_argument("--outdir", required=True, help="dir for aica_pool.{c,bin} + aica_sample_table.c")
    ap.add_argument("--incdir", help="dir for aica_sample_table.h (default: outdir)")
    a = ap.parse_args()
    main(a.ctl, a.tbl, a.outdir, a.incdir or a.outdir)
